### ISSUE TITLE
Share product setup

### ISSUE THREAD

**Issue by sdruskat** [nakag/gef5.mvc.examples#1]
Hi,

I've tried to run stage one of your examples on Java 8 (Linux) and a Neon-based taret platform with GEF 5.0.2. I cannot get it to work, as it throws a ClassNotFoundException: javafx.beans.value.ChangeListener.

Could you perhaps share the platform you got this to run on? E.g., target platform and run config? That would be great and help me very much!

Thanks!

**Comment by nakag** [comment]
Hi, sorry I delayed to reply.

It might jfxrt.jar is not listed in Libraties in your project.

If so, please add jfxrt.jar in java build path.
it is in ${JAVA_HOME}/jre/lib/ext .
Or, add access role in JRE System Library.

<img width="847" alt="2018-03-08 8 49 11" src="https://user-images.githubusercontent.com/3157383/37124898-adbba2ee-22ad-11e8-8ff0-296bfdcf41b0.png">

**Comment by sdruskat** [comment]
Thanks @nakag! My issue was that I used an extension point for the plugin providing the editor, rather than `fragment.e4xmi`, hence I ran into classloader problems, even when setting `-Dosgi.framework.extensions=org.eclipse.fx.osgi`. Refactoring to use the application model instead solved my issue.

Best of luck with your project!
