### ISSUE TITLE
Application empty in examples

### ISSUE THREAD

**Issue by Jmales** [nakag/gef5.mvc.examples#2]
Hello. First of all thank you for the examples.

Can you provide some screenshots of each of the 6 examples? I imported the examples and ran the application but all I see is a new empty Eclipse window. Am I doing something wrong?

**Comment by nakag** [comment]
Hello.Thanks for trying these examples.

It's example6 (in progress...) screen capture.
<img width="1028" alt="example6" src="https://user-images.githubusercontent.com/3157383/43985336-aa1e8232-9d41-11e8-980b-cd6c6d44d0db.png">

Make project and create a file ("tmdx" extension).
And then, open with example editor.

**Comment by Jmales** [comment]
Thank you for the answer mate ;)

I can do it now
